global using Carter;
global using Mapster;
global using MediatR;
global using eCommerceMicroservices2.BuildingBlocks.CQRS;
global using eCommerceMicroservicesV2.Catalog.API.Models;
global using Marten;
global using eCommerceMicroservicesV2.Catalog.API.Exceptions;
global using FluentValidation;
global using eCommerceMicroservices2.BuildingBlocks.Exceptions;